### ISSUE TITLE
Improve LFO defaults (og to xd)

### ISSUE THREAD

**Issue by Christedge** [gazzar/loguetools#6]
- Using v0.1.5 binary as of June 14 to convert minilogue ("OG") patches to xd.
- Raising LFO intensity often does not provide an audible effect. The reason is that Program edit menu, button 4, LFO target oscillator points to VCO 2 only instead of 1+2 or "all". I had to edit that for each particular patch.
- LFO EG mode points to 1Shot per default. Normal would be a better choice IMO.

**Comment by gazzar** [comment]
I'll take a look at this. It sounds like a reasonable idea.

**Comment by gazzar** [comment]
@Christedge The current logic in my code tries to prioritise pitch and filter envelope changes higher than LFO changes because the minilogue xd has fewer routing options than the og minilogue in this area. My reasoning for doing it this way is that the attack portion of any filter or pitch envelope has more influence on the timbre than the LFO has during the envelope sustain portion. Therefore, the LFO is sacrificed in these cases and used in 1-shot mode targeting OSC2. I could change the logic here, or change the thresholds that are used to set the priorities. It's not obvious what to do without having both synths to enable me to test the effect on a number of different patches. If you're willing to be a beta tester for this, I could flip the logic to prioritise the LFO over say, filter pitch. My thinking is that patches that rely on pitch envelope are probably rare. What do you think?

**Comment by Christedge** [comment]
Actually the og already left my flat, since I imported everything of interest to the xd (and meanwhile to the pl). So I have the same problem, I could not do end-to-end tests in case the logic changes.
Routing the LFO as 1shot to VCO2 makes totally sense, since during the conversion I've seem two fistful of patches that make good use of it by setting sync for osc 2 and applying ring/fm to create interesting transients (which the pl partly cannot do). But still, in most patches, the LFO is used in normal mode and applied to all oscillators to create traditional vibrato effects.
My two cents of guesswork: Set LFO to normal and route it to all oscillators, but only in case that LFO Int is set to 0. So users get instant vibrato (as they might expect) as they raise LFO Int.
Alternatively, just close this ticket :) .

**Comment by gazzar** [comment]
Thanks for the feedback. I'm tempted to change the logic a bit, but I'll have to think about what to do. Currently, if the LFO Int is numerically higher than the pitch and cutoff values, it is already routed to both oscillators, but it's probably very rare that a patch does that, and numerical comparison doesn't give any sense of how much they each affect the timbre.

**Comment by gazzar** [comment]
I've tweaked the logic a bit, so the lfo is prioritised higher now. It seems to get more conversions right now.
